=== kineticedge/ktools/ktools-cli/src/test/resources/schemas/purchaseOrder.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$type": {
      "type": "string"
    },
    "timestamp": {
      "type": "number"
    },
    "orderId": {
      "type": "string"
    },
    "userId": {
      "type": "string"
    },
    "storeId": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "sku": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          },
          "quotedPrice": {
            "type": ["number", "null"]
          },
          "price": {
            "type": ["number", "null"]
          }
        },
        "required": ["sku", "quantity"]
      }
    },
    "tax": {
      "type": ["number", "null"]
    },
    "user": {
      "type": ["object", "null"]
    },
    "store": {
      "type": ["object", "null"]
    }
  },
  "required": [
    "$type",
    "timestamp",
    "orderId",
    "userId",
    "storeId",
    "items"
  ]
}

=== kineticedge/ktools/ktools-cli/src/test/resources/example.json
{
  "$type": "io.kineticedge.ksd.common.domain.PurchaseOrder",
  "timestamp": 1710077837.168611172,
  "orderId": "SV-00001549",
  "userId": "5066",
  "storeId": "180",
  "items": [
    {
      "sku": "001",
      "quantity": 3,
      "quotedPrice": null,
      "price": null
    },
    {
      "sku": "002",
      "quantity": 8,
      "quotedPrice": null,
      "price": null
    },
    {
      "sku": "010",
      "quantity": 2,
      "quotedPrice": null,
      "price": null
    },
    {
      "sku": "234",
      "quantity": 3,
      "quotedPrice": null,
      "price": null
    }
  ],
  "tax": null,
  "user": null,
  "store": null
}
